// === BEGIN _source_policy (generated by scripts/p2_source_policy.js -- edit scripts/nodes/_source_policy.js) ===
const SOURCE_POLICY = (function () {
  const ATS_URL = /(boards(-api)?\.greenhouse\.io|job-boards\.greenhouse\.io|greenhouse\.io|gh_jid=|jobs\.lever\.co|lever\.co|jobs\.ashbyhq\.com|ashbyhq\.com|ashby_jid=|workable\.com|recruitee\.com|smartrecruiters\.com|myworkdayjobs\.com|workday\.com|icims\.com|jobvite\.com|bamboohr\.com|breezy\.hr|teamtailor\.com|taleo\.net|successfactors|oraclecloud\.com|amazon\.jobs|jobs\.apple\.com|careers\.microsoft\.com|metacareers\.com|google\.com\/about\/careers|careers\.google\.com|netflix\.net|joinbytedance\.com|lifeattiktok\.com|eightfold)/i;
  const BOARD_DENY = /(instahyre|wellfound|angel\.co|hirist|cutshort|foundit|naukri|shine\.com|monster\.|indeed\.|glassdoor|ziprecruiter|dice\.com|simplyhired|jooble|jobgether|talent\.com|whatjobs|careerjet|jobrapido|neuvoo|trabajo|bebee|productbased|ambitionbox|expertia|linkedin\.com|remoteok|weworkremotely|himalayas\.app|remotive|jobicy|arbeitnow|remote\.co\b|flexjobs|nodesk|otta\.io|cord\.co\b)/i;
  const CAREERS_SUB = /(^|\.)(jobs|careers|career|join|work|workfor|boards|apply|talent|hire|recruiting|jobsearch)\./i;
  const CAREERS_PATH = /\/(jobs?|careers?|join|openings?|positions?|opportunities|vacancies|work-with-us|life-?at)\b/i;
  function escapeRegex(s) { return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
  function classifyUrlTier(url) {
    if (!url) return { tier: 4, label: 'invalid' };
    const u = url.toLowerCase();
    // TIER 1 — Direct ATS platforms
    if (/(?:boards|job-boards)\.greenhouse\.io/.test(u)) return { tier: 1, label: 'ats:greenhouse' };
    if (/jobs\.lever\.co/.test(u)) return { tier: 1, label: 'ats:lever' };
    if (/jobs\.ashbyhq\.com/.test(u)) return { tier: 1, label: 'ats:ashby' };
    if (/[\w-]+\.wd\d+\.myworkdayjobs\.com/.test(u)) return { tier: 1, label: 'ats:workday' };
    if (/apply\.workable\.com/.test(u)) return { tier: 1, label: 'ats:workable' };
    if (/jobs\.smartrecruiters\.com/.test(u)) return { tier: 1, label: 'ats:smartrecruiters' };
    if (/workatastartup\.com\/jobs\//.test(u)) return { tier: 1, label: 'ats:yc' };
    if (/[\w-]+\.recruitee\.com/.test(u)) return { tier: 1, label: 'ats:recruitee' };
    if (/[\w-]+\.personio\.(com|de)/.test(u)) return { tier: 1, label: 'ats:personio' };
    if (/[\w-]+\.bamboohr\.com/.test(u)) return { tier: 1, label: 'ats:bamboohr' };
    if (/[\w-]+\.jobvite\.com/.test(u)) return { tier: 1, label: 'ats:jobvite' };
    if (/careers-[\w-]+\.icims\.com/.test(u)) return { tier: 1, label: 'ats:icims' };
    if (/[\w-]+\.taleo\.net/.test(u)) return { tier: 1, label: 'ats:taleo' };
    if (/successfactors\.(com|eu)/.test(u)) return { tier: 1, label: 'ats:successfactors' };
    if (/[\w-]+\.eightfold\.ai/.test(u)) return { tier: 1, label: 'ats:eightfold' };
    // TIER 2 — Curated remote/aggregator boards
    if (/weworkremotely\.com\/(remote-jobs|listings)\//.test(u)) return { tier: 2, label: 'curated:wwr' };
    if (/remoteok\.(com|io)/.test(u)) return { tier: 2, label: 'curated:remoteok' };
    if (/himalayas\.app\/jobs\//.test(u)) return { tier: 2, label: 'curated:himalayas' };
    if (/remotive\.(com|io)\/(jobs|remote-jobs)\//.test(u)) return { tier: 2, label: 'curated:remotive' };
    if (/jobicy\.com/.test(u)) return { tier: 2, label: 'curated:jobicy' };
    if (/wellfound\.com\/jobs\//.test(u)) return { tier: 2, label: 'curated:wellfound' };
    if (/arbeitnow\.com\/jobs\//.test(u)) return { tier: 2, label: 'curated:arbeitnow' };
    if (/ai-jobs\.net\/job\//.test(u)) return { tier: 2, label: 'curated:aijobs' };
    if (/builtin(nyc|sf|la|chicago|seattle|boston|austin)?\.com\/job\//.test(u)) return { tier: 2, label: 'curated:builtin' };
    // TIER 3 — General web aggregators (often listings pages, low signal)
    if (/linkedin\.com/.test(u)) return { tier: 3, label: 'aggregator:linkedin' };
    if (/indeed\.com/.test(u)) return { tier: 3, label: 'aggregator:indeed' };
    if (/glassdoor\.com/.test(u)) return { tier: 3, label: 'aggregator:glassdoor' };
    if (/ziprecruiter\.com/.test(u)) return { tier: 3, label: 'aggregator:ziprecruiter' };
    if (/dice\.com/.test(u)) return { tier: 3, label: 'aggregator:dice' };
    if (/monster\.com/.test(u)) return { tier: 3, label: 'aggregator:monster' };
    if (/simplyhired\.com/.test(u)) return { tier: 3, label: 'aggregator:simplyhired' };
    if (/careerbuilder\.com/.test(u)) return { tier: 3, label: 'aggregator:careerbuilder' };
    if (/snagajob\.com/.test(u)) return { tier: 3, label: 'aggregator:snagajob' };
    if (/theladders\.com/.test(u)) return { tier: 3, label: 'aggregator:theladders' };
    if (/jora\.com/.test(u)) return { tier: 3, label: 'aggregator:jora' };
    if (/talent\.com/.test(u)) return { tier: 3, label: 'aggregator:talent' };
    if (/jobs2careers\.com/.test(u)) return { tier: 3, label: 'aggregator:jobs2careers' };
    // TIER 2.5 — Plausible career page on unrecognized domain
    if (/^https?:\/\/(careers|jobs|apply|hiring|talent|work|join)\.[\w-]+\.[\w.]+/.test(u)) {
      return { tier: 2.5, label: 'career:subdomain' };
    }
    if (/\/(careers|jobs|join-us|join_us|apply|positions|openings|opportunities|vacancies|hiring|work-with-us)\//.test(u)) {
      return { tier: 2.5, label: 'career:path' };
    }
    // TIER 4 — Anything else
    return { tier: 4, label: 'unknown' };
  }
  function isAtsDestination(j){
    const raw = j.apply_url || j.url || '';
    if (!raw) return false;
    const low = raw.toLowerCase();
    if (BOARD_DENY.test(low)) return false;        // generic board / marketplace / easy-apply -> BAN
    if (ATS_URL.test(low)) return true;            // recognized ATS host / embed marker
    let host = '', pathx = '';
    try { const u = new URL(raw); host = u.hostname.toLowerCase(); pathx = u.pathname.toLowerCase(); }
    catch (e) { return false; }
    const dom = (j.company_domain || '').toLowerCase().replace(/^www\./, '');
    if (dom && (host === dom || host.endsWith('.' + dom))) return true;   // company's own domain
    if (CAREERS_SUB.test(host)) return true;       // careers.x.com / jobs.x.com sub-domain portal
    if (CAREERS_PATH.test(pathx)) return true;     // company.com/careers, company.com/jobs portal
    return false;                                  // unknown host -> fail closed (policy)
  }
  function standardAtsDomains() { return [ 'boards.greenhouse.io', 'job-boards.greenhouse.io', 'jobs.lever.co', 'jobs.ashbyhq.com', 'apply.workable.com', 'myworkdayjobs.com', 'jobs.smartrecruiters.com', 'workatastartup.com' ]; }
  return { ATS_URL, BOARD_DENY, CAREERS_SUB, CAREERS_PATH, escapeRegex, classifyUrlTier, isAtsDestination, standardAtsDomains };
})();
// === END _source_policy ===

// Source policy (ATS allow / board deny / career heuristics / isAtsDestination)
// is centralized in _source_policy.js, inlined above as SOURCE_POLICY (P2).
const isAtsDestination = SOURCE_POLICY.isAtsDestination;

// Aggregate Jobs v10 — composite-key dedup (S2d) + cache-first ordering (Phase 3).
// Changes vs v9:
//   - Dedup collision now prefers the CACHE copy on an equal-tier tie (source_priority),
//     and backfills rrf_score/source_priority from the dropped dup.
//   - Sort is cache-first: source_priority (cache=0) -> cache rrf_score -> tier -> recency,
//     so the cache's hybrid relevance survives instead of being flattened to tier+date.
//   - Recency uses posted_at when present (falls back to updated_at).

const sourceCounts = {};
const byKey = new Map(); // dedup key -> kept job (a job may be reachable by several keys)

function dedupKeys(job) {
  const ks = [];
  if (job.url) ks.push('u:' + job.url.replace(/[?#].*$/, '').replace(/\/+$/, '').toLowerCase());
  const ct = ((job.company || '') + '|' + (job.title || '')).toLowerCase().replace(/\s+/g, ' ').trim();
  if (ct.replace(/\|/g, '').length > 4) ks.push('ct:' + ct);
  return ks;
}

for (const item of $input.all()) {
  const jobs = item.json.jobs || [];
  const source = item.json.source || 'unknown';
  sourceCounts[source] = (sourceCounts[source] || 0) + jobs.length;
  for (const job of jobs) {
    if (!job || !job.url) continue;
    const ks = dedupKeys(job);
    let existing = null;
    for (const k of ks) { if (byKey.has(k)) { existing = byKey.get(k); break; } }
    if (!existing) { for (const k of ks) byKey.set(k, job); continue; }
    // collision: keep lower tier; on an equal-tier tie keep the cache copy
    // (source_priority 0). Backfill salary/location/rrf from the dropped dup.
    const curTier = existing.source_tier || 99;
    const newTier = job.source_tier || 99;
    const curP = existing.source_priority ?? 1;
    const newP = job.source_priority ?? 1;
    const takeNew = newTier < curTier || (newTier === curTier && newP < curP);
    const keep = takeNew ? job : existing;
    const drop = takeNew ? existing : job;
    if (!keep.salary_min && drop.salary_min) { keep.salary_min = drop.salary_min; keep.salary_max = drop.salary_max; keep.salary_currency = drop.salary_currency; }
    if ((!keep.location || keep.location === 'unknown') && drop.location && drop.location !== 'unknown') keep.location = drop.location;
    if (!keep.rrf_score && drop.rrf_score) keep.rrf_score = drop.rrf_score;
    if (!keep.tier && drop.tier) keep.tier = drop.tier;
    if (keep.source_priority == null && drop.source_priority != null) keep.source_priority = drop.source_priority;
    for (const k of dedupKeys(existing)) byKey.set(k, keep);
    for (const k of ks) byKey.set(k, keep);
  }
}

const allJobs = Array.from(new Set(byKey.values()));

const expandCtx = $('Parse Expand Query').first().json;
const roleFamilies    = expandCtx.role_families    || [];
const excludedRoles   = expandCtx.excluded_roles   || [];
const locationCanon   = (expandCtx.location_canonical || '').trim().toLowerCase();
const remotePref      = expandCtx.remote_preference  || 'open';
const includeInterns  = !!expandCtx.include_interns;   // S1: intent-driven intern gate
const companyRx       = (expandCtx.company_rx || '').trim();   // B: named-employer filter (alias-expanded in Parse)
const wantCountry     = (expandCtx.country || '').trim().toUpperCase() || null;   // 1b: queried ISO-2 (web-lane country guard)
const freshness       = expandCtx.freshness          || 'qdr:w';

const freshnessMs = { 'qdr:h': 3600000, 'qdr:d': 86400000, 'qdr:w': 604800000, 'qdr:m': 2592000000, 'qdr:y': 31536000000 }[freshness] || 604800000;
const cutoff = Date.now() - freshnessMs;

let filtered = allJobs;

// Drop Tier 3 aggregators and Tier 4 unknown pages from the main ranked results.
filtered = filtered.filter(j => (j.source_tier || 4) < 3);

// S1: drop intern/trainee/apprentice/hackathon roles ONLY when the query didn't ask for
// them (web lanes bypass the cache prefilter, so the gate must also run here).
if (!includeInterns) filtered = filtered.filter(j => !/\b(intern(ship)?|trainee|apprentice|co-?op|hackathon)\b/i.test(j.title || ''));

const LISTING_TITLE = /(\d{2,}\+?\s+[\w\s/,&.+-]*\bjobs\b|\bjobs\s+in\s+[a-z]|\bjob\s+openings?\b)/i;
const STAFFING = /(smart[\s-]?working|wissen|collabera|diverse[\s-]?lynx|mindlance|nityo|sysmind|aptask|\bartech\b|teksystems|mastech|talent\s?500|jobgether|surely[\s-]?placed|kwan\s?ventures|staffing|consultancy\s+services|outsourc|manpower|randstad|kforce|infotech)/i;
filtered = filtered.filter(j => {
  if (!isAtsDestination(j)) return false;        // ATS / company-portal apply only
  if (LISTING_TITLE.test(j.title || '')) return false;
  const hay = ((j.company || '') + ' ' + (j.title || '') + ' ' + (j.url || '')).toLowerCase();
  if (STAFFING.test(hay)) return false;
  return true;
});

// B: company targeting. When the user named an employer, keep ONLY that employer.
// company_rx is the alias-expanded alternation built in Parse Expand Query
// ("amazon|aws|audible|twitch"). Cache jobs are already company-gated in SQL; this
// also constrains the web lanes and stays the single match definition for both.
if (companyRx) {
  let rx = null; try { rx = new RegExp('\\b(' + companyRx + ')\\b', 'i'); } catch (e) {}
  if (rx) filtered = filtered.filter(j => rx.test((j.company || '') + ' ' + (j.url || '')));
}

// Role family filter
if (roleFamilies.length > 0) {
  filtered = filtered.filter(j => {
    const haystack = (j.title + ' ' + (j.department || '')).toLowerCase();
    if (excludedRoles.some(excl => {
      const terms = excl.toLowerCase().split(/\s+/);
      return terms.every(t => new RegExp('\\b' + t + '\\b').test(haystack));
    })) return false;
    return roleFamilies.some(variant => {
      const terms = variant.toLowerCase().split(/\s+/).filter(t => t.length > 1);
      return terms.every(term => term.length <= 3
        ? new RegExp('\\b' + term + '\\b').test(haystack)
        : haystack.includes(term));
    });
  });
}

// L2: location filter. Cache jobs (source_priority 0 / geocoded) are already geo-gated in
// hybrid_cache_search.sql (gazetteer country gate + soft proximity), so they pass through
// here; web-lane jobs carry no resolved geo, so string-match them against the requested
// place. The old 13-city LOC_SYN/LOC_COUNTRY map is gone -- the worldwide gazetteer in SQL
// handles the cache (the bulk); web is a small supplement.
// 1b: web-lane country scan. Mirror of geo.py COUNTRY_ISO/_countries_in -- full names + safe
// short forms (us/usa/uk/uae) ONLY, NEVER bare 2-letter codes (they collide with US state
// codes). MAINTAIN IN LOCKSTEP with services/matcher/geo.py COUNTRY_ISO.
const CC_MAP = { 'usa':'US','united states':'US','united states of america':'US','america':'US','us':'US',
  'uk':'GB','united kingdom':'GB','england':'GB','britain':'GB','great britain':'GB','scotland':'GB','wales':'GB',
  'india':'IN','bharat':'IN','canada':'CA','australia':'AU','germany':'DE','deutschland':'DE','france':'FR',
  'ireland':'IE','netherlands':'NL','holland':'NL','spain':'ES','italy':'IT','poland':'PL','portugal':'PT',
  'sweden':'SE','switzerland':'CH','singapore':'SG','japan':'JP','china':'CN','brazil':'BR','mexico':'MX',
  'israel':'IL','uae':'AE','united arab emirates':'AE','new zealand':'NZ','south africa':'ZA','philippines':'PH',
  'indonesia':'ID','vietnam':'VN','argentina':'AR','colombia':'CO','chile':'CL','nigeria':'NG','egypt':'EG',
  'turkey':'TR','ukraine':'UA','romania':'RO','austria':'AT','belgium':'BE','denmark':'DK','finland':'FI',
  'norway':'NO','greece':'GR','czechia':'CZ','czech republic':'CZ','hungary':'HU','south korea':'KR','korea':'KR',
  'hong kong':'HK','taiwan':'TW','malaysia':'MY','thailand':'TH','saudi arabia':'SA','kenya':'KE','pakistan':'PK',
  'bangladesh':'BD','sri lanka':'LK' };
const CC_TERMS = Object.keys(CC_MAP).sort((a, b) => b.length - a.length);
const CC_RX = new RegExp('\\b(' + CC_TERMS.map(t => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')\\b', 'ig');
function countriesIn(text){
  const out = new Set(); if (!text) return out;
  CC_RX.lastIndex = 0; let m;
  while ((m = CC_RX.exec(text))) { const cc = CC_MAP[m[1].toLowerCase()]; if (cc) out.add(cc); }
  return out;
}
function isBareRemote(loc){
  return /\bremote\b/.test(loc) &&
    loc.replace(/\bremote\b/g,'').replace(/\b(work\s*from\s*home|wfh|anywhere|global|fully|hybrid|first|friendly|ok|only|optional|based)\b/g,'').replace(/[^a-z]/g,'').length === 0;
}
const wantPlace = (locationCanon && !['any','anywhere','worldwide','global','remote'].includes(locationCanon))
  ? locationCanon.split(',')[0].trim() : null;
if (wantPlace && remotePref !== 'remote_only') {
  filtered = filtered.filter(j => {
    if (j.source_priority === 0 || j.country_iso) return true;          // cache / geocoded: already SQL geo-gated
    const loc = (j.location || '').toLowerCase();
    const lt = loc + ' ' + (j.title || '').toLowerCase();
    if (lt.includes(wantPlace)) return true;                            // web job names the requested place
    // 1b: if the web job's LOCATION names countries, keep ONLY when the queried country is among
    // them ("Remote USA" for an India query -> {US}, no IN -> drop). Scan loc only (a title saying
    // "remote" is fine; misleading country text lives in the structured location field).
    if (wantCountry) {
      const ccs = countriesIn(loc);
      if (ccs.size) return ccs.has(wantCountry);
    }
    if (isBareRemote(loc)) return true;                                 // truly unqualified remote -> worldwide
    if (!loc.trim() && /\bremote\b/.test(lt)) return true;              // empty loc + remote-in-title -> worldwide
    return false;
  });
}

// Recency filter (soft) — prefer posted_at, fall back to updated_at
filtered = filtered.filter(j => {
  const d = j.posted_at || j.updated_at;
  if (!d) return true;
  const t = new Date(d).getTime();
  return isNaN(t) || t >= cutoff;
});

// Cache-first sort: cache (source_priority 0) leads, ordered by its hybrid rrf
// relevance; then tier; then recency. Web fills the tail.
filtered.sort((a, b) => {
  const pa = a.source_priority ?? 1, pb = b.source_priority ?? 1;
  if (pa !== pb) return pa - pb;
  if (pa === 0) {
    const ra = a.rrf_score || 0, rb = b.rrf_score || 0;
    if (rb !== ra) return rb - ra;
  }
  const tierDiff = (a.source_tier || 99) - (b.source_tier || 99);
  if (tierDiff !== 0) return tierDiff;
  const ad = new Date(a.posted_at || a.updated_at || 0).getTime() || 0;
  const bd = new Date(b.posted_at || b.updated_at || 0).getTime() || 0;
  return bd - ad;
});

// Tier composition for downstream display
const tierCounts = { 1: 0, 2: 0, '2.5': 0, 3: 0 };
for (const j of filtered) {
  const t = j.source_tier;
  if (t === 1) tierCounts[1]++;
  else if (t === 2) tierCounts[2]++;
  else if (t === 2.5) tierCounts['2.5']++;
  else if (t === 3) tierCounts[3]++;
}

const top = filtered.slice(0, 50);
return [{ json: {
  jobs: top, count: top.length, total_raw: allJobs.length,
  sources: sourceCounts, tier_counts: tierCounts,
  filter_applied: { role_families: roleFamilies, location: locationCanon || null, remote_preference: remotePref, companies: expandCtx.companies || [] }
} }];
