// === BEGIN _source_policy (generated by scripts/p2_source_policy.js -- edit scripts/nodes/_source_policy.js) ===
const SOURCE_POLICY = (function () {
  const ATS_URL = /(boards(-api)?\.greenhouse\.io|job-boards\.greenhouse\.io|greenhouse\.io|gh_jid=|jobs\.lever\.co|lever\.co|jobs\.ashbyhq\.com|ashbyhq\.com|ashby_jid=|workable\.com|recruitee\.com|smartrecruiters\.com|myworkdayjobs\.com|workday\.com|icims\.com|jobvite\.com|bamboohr\.com|breezy\.hr|teamtailor\.com|taleo\.net|successfactors|oraclecloud\.com|amazon\.jobs|jobs\.apple\.com|careers\.microsoft\.com|metacareers\.com|google\.com\/about\/careers|careers\.google\.com|netflix\.net|joinbytedance\.com|lifeattiktok\.com|eightfold)/i;
  const BOARD_DENY = /(instahyre|wellfound|angel\.co|hirist|cutshort|foundit|naukri|shine\.com|monster\.|indeed\.|glassdoor|ziprecruiter|dice\.com|simplyhired|jooble|jobgether|talent\.com|whatjobs|careerjet|jobrapido|neuvoo|trabajo|bebee|productbased|ambitionbox|expertia|linkedin\.com|remoteok|weworkremotely|himalayas\.app|remotive|jobicy|arbeitnow|remote\.co\b|flexjobs|nodesk|otta\.io|cord\.co\b)/i;
  const CAREERS_SUB = /(^|\.)(jobs|careers|career|join|work|workfor|boards|apply|talent|hire|recruiting|jobsearch)\./i;
  const CAREERS_PATH = /\/(jobs?|careers?|join|openings?|positions?|opportunities|vacancies|work-with-us|life-?at)\b/i;
  function escapeRegex(s) { return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
  function classifyUrlTier(url) {
    if (!url) return { tier: 4, label: 'invalid' };
    const u = url.toLowerCase();
    // TIER 1 — Direct ATS platforms
    if (/(?:boards|job-boards)\.greenhouse\.io/.test(u)) return { tier: 1, label: 'ats:greenhouse' };
    if (/jobs\.lever\.co/.test(u)) return { tier: 1, label: 'ats:lever' };
    if (/jobs\.ashbyhq\.com/.test(u)) return { tier: 1, label: 'ats:ashby' };
    if (/[\w-]+\.wd\d+\.myworkdayjobs\.com/.test(u)) return { tier: 1, label: 'ats:workday' };
    if (/apply\.workable\.com/.test(u)) return { tier: 1, label: 'ats:workable' };
    if (/jobs\.smartrecruiters\.com/.test(u)) return { tier: 1, label: 'ats:smartrecruiters' };
    if (/workatastartup\.com\/jobs\//.test(u)) return { tier: 1, label: 'ats:yc' };
    if (/[\w-]+\.recruitee\.com/.test(u)) return { tier: 1, label: 'ats:recruitee' };
    if (/[\w-]+\.personio\.(com|de)/.test(u)) return { tier: 1, label: 'ats:personio' };
    if (/[\w-]+\.bamboohr\.com/.test(u)) return { tier: 1, label: 'ats:bamboohr' };
    if (/[\w-]+\.jobvite\.com/.test(u)) return { tier: 1, label: 'ats:jobvite' };
    if (/careers-[\w-]+\.icims\.com/.test(u)) return { tier: 1, label: 'ats:icims' };
    if (/[\w-]+\.taleo\.net/.test(u)) return { tier: 1, label: 'ats:taleo' };
    if (/successfactors\.(com|eu)/.test(u)) return { tier: 1, label: 'ats:successfactors' };
    if (/[\w-]+\.eightfold\.ai/.test(u)) return { tier: 1, label: 'ats:eightfold' };
    // TIER 2 — Curated remote/aggregator boards
    if (/weworkremotely\.com\/(remote-jobs|listings)\//.test(u)) return { tier: 2, label: 'curated:wwr' };
    if (/remoteok\.(com|io)/.test(u)) return { tier: 2, label: 'curated:remoteok' };
    if (/himalayas\.app\/jobs\//.test(u)) return { tier: 2, label: 'curated:himalayas' };
    if (/remotive\.(com|io)\/(jobs|remote-jobs)\//.test(u)) return { tier: 2, label: 'curated:remotive' };
    if (/jobicy\.com/.test(u)) return { tier: 2, label: 'curated:jobicy' };
    if (/wellfound\.com\/jobs\//.test(u)) return { tier: 2, label: 'curated:wellfound' };
    if (/arbeitnow\.com\/jobs\//.test(u)) return { tier: 2, label: 'curated:arbeitnow' };
    if (/ai-jobs\.net\/job\//.test(u)) return { tier: 2, label: 'curated:aijobs' };
    if (/builtin(nyc|sf|la|chicago|seattle|boston|austin)?\.com\/job\//.test(u)) return { tier: 2, label: 'curated:builtin' };
    // TIER 3 — General web aggregators (often listings pages, low signal)
    if (/linkedin\.com/.test(u)) return { tier: 3, label: 'aggregator:linkedin' };
    if (/indeed\.com/.test(u)) return { tier: 3, label: 'aggregator:indeed' };
    if (/glassdoor\.com/.test(u)) return { tier: 3, label: 'aggregator:glassdoor' };
    if (/ziprecruiter\.com/.test(u)) return { tier: 3, label: 'aggregator:ziprecruiter' };
    if (/dice\.com/.test(u)) return { tier: 3, label: 'aggregator:dice' };
    if (/monster\.com/.test(u)) return { tier: 3, label: 'aggregator:monster' };
    if (/simplyhired\.com/.test(u)) return { tier: 3, label: 'aggregator:simplyhired' };
    if (/careerbuilder\.com/.test(u)) return { tier: 3, label: 'aggregator:careerbuilder' };
    if (/snagajob\.com/.test(u)) return { tier: 3, label: 'aggregator:snagajob' };
    if (/theladders\.com/.test(u)) return { tier: 3, label: 'aggregator:theladders' };
    if (/jora\.com/.test(u)) return { tier: 3, label: 'aggregator:jora' };
    if (/talent\.com/.test(u)) return { tier: 3, label: 'aggregator:talent' };
    if (/jobs2careers\.com/.test(u)) return { tier: 3, label: 'aggregator:jobs2careers' };
    // TIER 2.5 — Plausible career page on unrecognized domain
    if (/^https?:\/\/(careers|jobs|apply|hiring|talent|work|join)\.[\w-]+\.[\w.]+/.test(u)) {
      return { tier: 2.5, label: 'career:subdomain' };
    }
    if (/\/(careers|jobs|join-us|join_us|apply|positions|openings|opportunities|vacancies|hiring|work-with-us)\//.test(u)) {
      return { tier: 2.5, label: 'career:path' };
    }
    // TIER 4 — Anything else
    return { tier: 4, label: 'unknown' };
  }
  function isAtsDestination(j){
    const raw = j.apply_url || j.url || '';
    if (!raw) return false;
    const low = raw.toLowerCase();
    if (BOARD_DENY.test(low)) return false;        // generic board / marketplace / easy-apply -> BAN
    if (ATS_URL.test(low)) return true;            // recognized ATS host / embed marker
    let host = '', pathx = '';
    try { const u = new URL(raw); host = u.hostname.toLowerCase(); pathx = u.pathname.toLowerCase(); }
    catch (e) { return false; }
    const dom = (j.company_domain || '').toLowerCase().replace(/^www\./, '');
    if (dom && (host === dom || host.endsWith('.' + dom))) return true;   // company's own domain
    if (CAREERS_SUB.test(host)) return true;       // careers.x.com / jobs.x.com sub-domain portal
    if (CAREERS_PATH.test(pathx)) return true;     // company.com/careers, company.com/jobs portal
    return false;                                  // unknown host -> fail closed (policy)
  }
  function standardAtsDomains() { return [ 'boards.greenhouse.io', 'job-boards.greenhouse.io', 'jobs.lever.co', 'jobs.ashbyhq.com', 'apply.workable.com', 'myworkdayjobs.com', 'jobs.smartrecruiters.com', 'workatastartup.com' ]; }
  return { ATS_URL, BOARD_DENY, CAREERS_SUB, CAREERS_PATH, escapeRegex, classifyUrlTier, isAtsDestination, standardAtsDomains };
})();
// === END _source_policy ===

// Build FC Queries v3 — deterministic site:ATS coverage (mirrors You.com/Serper).
// Firecrawl was open-web searching (returned Naukri/Indeed aggregators); now we
// bake site:ATS into the query string so it targets real ATS postings, and it
// always fires when a role exists (no longer LLM-query dependent).
// Phase 3: cache-first — skip this PAID lane when the cache already returned enough.
const ctx = $('Parse Expand Query').first().json;
const llmQueries = ctx.firecrawl_queries || [];
const roles = ctx.role_families || [];

if (!roles.length && !llmQueries.length) {
  return [{ json: { _disabled: true, source: 'firecrawl', reason: 'No queries and no role_families' } }];
}

// Cache-first gate: if the cache lane already produced enough, don't pay for web.
// Best-effort cross-branch read; if Cache Prefilter hasn't executed yet we degrade
// to running the lane (safe — never worse than current behavior).
let _cacheCount = 0;
try { _cacheCount = ($('Cache Prefilter').first().json || {}).count || 0; } catch (e) {}
if (_cacheCount >= 25) {
  return [{ json: { _disabled: true, source: 'firecrawl', reason: 'cache_sufficient:' + _cacheCount } }];
}

const top = roles.slice(0, 2);
const loc = (ctx.location_canonical || '').split(',')[0].trim();
const locPart = loc ? ' "' + loc + '"' : '';
const role0 = top[0] || '';
const role1 = top[1] || top[0] || '';
const remoteOnly = ctx.remote_preference === 'remote_only';
// P1: remote_only adds a "remote" keyword to the SAME company-direct ATS targets --
// it must NOT widen to third-party remote boards (those are opt-in lanes, not default).
const remoteKw = remoteOnly ? ' remote' : '';

const deterministic = role0 ? [
  'site:boards.greenhouse.io "' + role0 + '"' + locPart + remoteKw,
  'site:jobs.lever.co "' + role0 + '"' + locPart + remoteKw,
  '(site:jobs.ashbyhq.com OR site:apply.workable.com) "' + role0 + '"' + locPart + remoteKw,
  '(site:myworkdayjobs.com OR site:jobs.smartrecruiters.com) "' + role1 + '"' + locPart + remoteKw,
] : [];

const standardATS = SOURCE_POLICY.standardAtsDomains();
// P1: includeDomains stays company-direct ATS ONLY -- no remote-board widening.
const includeDomains = standardATS;
// P0: no silent US default -- omit country entirely when the query named none
// (the prompt's "do NOT assume US" rule must hold all the way to the web call).
const country = ctx.country || null;
const location = ctx.location_canonical || null;
const freshness = ctx.freshness || 'qdr:w';
const limit = remoteOnly ? 25 : 10;

const all = [...llmQueries, ...deterministic];
const seen = new Set();
const queries = [];
for (const q of all) {
  if (!q) continue;
  const k = String(q).toLowerCase().trim();
  if (k && !seen.has(k)) { seen.add(k); queries.push(q); }
}

return queries.slice(0, 4).map(query => ({
  json: {
    _disabled: false,
    query,
    bodyObj: { query, limit, includeDomains, tbs: freshness, ignoreInvalidURLs: true, ...(country ? { country } : {}), ...(location ? { location } : {}) }
  }
}));
