-- ═══════════════════════════════════════════════════════════════
--  Workday tenant seed (W2 + expand) — 182 CXS-VERIFIED employers (June 2026).
--  Firecrawl /search -> myworkdayjobs URL -> CXS-verified (total>0) -> name-match
--  guard + manual audit (dropped wrong-company FPs, rescued valid ticker tenants).
--  api_base = full CXS base URL. companies.tier='hot' (poll priority); desirability
--  tier in company_tiers (56 A / 126 B — re-tier freely). Idempotent.
--  Apply: docker exec -i careerforge_postgres psql -U careerforge -d careerforge < db/seed_workday.sql
-- ═══════════════════════════════════════════════════════════════

INSERT INTO companies (name, ats_type, slug, api_base, tier, is_active, next_poll_at, poll_interval) VALUES
  ('3M','workday','3m','https://3m.wd1.myworkdayjobs.com/wday/cxs/3m/Search','hot',true,now(),'6 hours'),
  ('Abbott','workday','abbott','https://abbott.wd5.myworkdayjobs.com/wday/cxs/abbott/abbottcareers','hot',true,now(),'6 hours'),
  ('Adobe','workday','adobe','https://adobe.wd5.myworkdayjobs.com/wday/cxs/adobe/external_experienced','hot',true,now(),'6 hours'),
  ('Agilent Technologies','workday','agilent','https://agilent.wd5.myworkdayjobs.com/wday/cxs/agilent/Agilent_Careers','hot',true,now(),'6 hours'),
  ('AIG','workday','aig','https://aig.wd1.myworkdayjobs.com/wday/cxs/aig/aig','hot',true,now(),'6 hours'),
  ('Albemarle','workday','albemarle','https://albemarle.wd5.myworkdayjobs.com/wday/cxs/albemarle/External','hot',true,now(),'6 hours'),
  ('Allstate','workday','allstate','https://allstate.wd5.myworkdayjobs.com/wday/cxs/allstate/allstate_careers','hot',true,now(),'6 hours'),
  ('Ameriprise Financial','workday','ameriprise','https://ameriprise.wd5.myworkdayjobs.com/wday/cxs/ameriprise/Ameriprise','hot',true,now(),'6 hours'),
  ('Amgen','workday','amgen','https://amgen.wd1.myworkdayjobs.com/wday/cxs/amgen/Careers','hot',true,now(),'6 hours'),
  ('Analog Devices','workday','analogdevices','https://analogdevices.wd1.myworkdayjobs.com/wday/cxs/analogdevices/External','hot',true,now(),'6 hours'),
  ('Applied Materials','workday','amat','https://amat.wd1.myworkdayjobs.com/wday/cxs/amat/External','hot',true,now(),'6 hours'),
  ('Assurant','workday','assurant','https://assurant.wd1.myworkdayjobs.com/wday/cxs/assurant/Assurant_Careers','hot',true,now(),'6 hours'),
  ('AstraZeneca','workday','astrazeneca','https://astrazeneca.wd3.myworkdayjobs.com/wday/cxs/astrazeneca/Careers','hot',true,now(),'6 hours'),
  ('AT&T','workday','att','https://att.wd1.myworkdayjobs.com/wday/cxs/att/ATTGeneral','hot',true,now(),'6 hours'),
  ('Autodesk','workday','autodesk','https://autodesk.wd1.myworkdayjobs.com/wday/cxs/autodesk/Ext','hot',true,now(),'6 hours'),
  ('Avantor','workday','vwr','https://vwr.wd1.myworkdayjobs.com/wday/cxs/vwr/avantorJobs','hot',true,now(),'6 hours'),
  ('Bank of America','workday','ghr','https://ghr.wd1.myworkdayjobs.com/wday/cxs/ghr/Lateral-US','hot',true,now(),'6 hours'),
  ('Baxter International','workday','baxter','https://baxter.wd1.myworkdayjobs.com/wday/cxs/baxter/baxter','hot',true,now(),'6 hours'),
  ('Becton Dickinson','workday','bdx','https://bdx.wd1.myworkdayjobs.com/wday/cxs/bdx/EXTERNAL_CAREER_SITE_USA','hot',true,now(),'6 hours'),
  ('Best Buy','workday','bestbuycanada','https://bestbuycanada.wd3.myworkdayjobs.com/wday/cxs/bestbuycanada/BestBuyCA_Career','hot',true,now(),'6 hours'),
  ('Biogen','workday','biibhr','https://biibhr.wd3.myworkdayjobs.com/wday/cxs/biibhr/external','hot',true,now(),'6 hours'),
  ('BlackRock','workday','blackrock','https://blackrock.wd1.myworkdayjobs.com/wday/cxs/blackrock/BlackRock_Professional','hot',true,now(),'6 hours'),
  ('Boeing','workday','boeing','https://boeing.wd1.myworkdayjobs.com/wday/cxs/boeing/EXTERNAL_CAREERS','hot',true,now(),'6 hours'),
  ('Bread Financial','workday','alliancedata','https://alliancedata.wd5.myworkdayjobs.com/wday/cxs/alliancedata/breadfinancial_US','hot',true,now(),'6 hours'),
  ('Bristol Myers Squibb','workday','bristolmyerssquibb','https://bristolmyerssquibb.wd5.myworkdayjobs.com/wday/cxs/bristolmyerssquibb/BMS','hot',true,now(),'6 hours'),
  ('Broadcom','workday','broadcom','https://broadcom.wd1.myworkdayjobs.com/wday/cxs/broadcom/External_Career','hot',true,now(),'6 hours'),
  ('C.H. Robinson','workday','chrobinson','https://chrobinson.wd5.myworkdayjobs.com/wday/cxs/chrobinson/CHRobinson','hot',true,now(),'6 hours'),
  ('Cadence Design Systems','workday','cadence','https://cadence.wd1.myworkdayjobs.com/wday/cxs/cadence/External_Careers','hot',true,now(),'6 hours'),
  ('Campbell Soup','workday','campbellsoup','https://campbellsoup.wd5.myworkdayjobs.com/wday/cxs/campbellsoup/ExternalCareers_GlobalSite','hot',true,now(),'6 hours'),
  ('Capital One','workday','capitalone','https://capitalone.wd12.myworkdayjobs.com/wday/cxs/capitalone/Capital_One','hot',true,now(),'6 hours'),
  ('Cardinal Health','workday','cardinalhealth','https://cardinalhealth.wd1.myworkdayjobs.com/wday/cxs/cardinalhealth/EXT','hot',true,now(),'6 hours'),
  ('Catalent','workday','catalent','https://catalent.wd1.myworkdayjobs.com/wday/cxs/catalent/External','hot',true,now(),'6 hours'),
  ('Caterpillar','workday','cat','https://cat.wd5.myworkdayjobs.com/wday/cxs/cat/CaterpillarCareers','hot',true,now(),'6 hours'),
  ('Cencora','workday','myhrabc','https://myhrabc.wd5.myworkdayjobs.com/wday/cxs/myhrabc/Global','hot',true,now(),'6 hours'),
  ('Centene','workday','centene','https://centene.wd5.myworkdayjobs.com/wday/cxs/centene/Centene_External','hot',true,now(),'6 hours'),
  ('Church & Dwight','workday','churchdwight','https://churchdwight.wd1.myworkdayjobs.com/wday/cxs/churchdwight/chdukcareers','hot',true,now(),'6 hours'),
  ('Cigna','workday','cigna','https://cigna.wd5.myworkdayjobs.com/wday/cxs/cigna/cignacareers','hot',true,now(),'6 hours'),
  ('Cisco','workday','cisco','https://cisco.wd5.myworkdayjobs.com/wday/cxs/cisco/Cisco_Careers','hot',true,now(),'6 hours'),
  ('Citi','workday','citi','https://citi.wd5.myworkdayjobs.com/wday/cxs/citi/2','hot',true,now(),'6 hours'),
  ('Clorox','workday','clorox','https://clorox.wd1.myworkdayjobs.com/wday/cxs/clorox/Clorox','hot',true,now(),'6 hours'),
  ('Comcast','workday','comcast','https://comcast.wd5.myworkdayjobs.com/wday/cxs/comcast/Comcast_Careers','hot',true,now(),'6 hours'),
  ('Conagra Brands','workday','conagrabrands','https://conagrabrands.wd1.myworkdayjobs.com/wday/cxs/conagrabrands/Careers_US','hot',true,now(),'6 hours'),
  ('Constellation Brands','workday','cbrands','https://cbrands.wd5.myworkdayjobs.com/wday/cxs/cbrands/CBI_External_Careers','hot',true,now(),'6 hours'),
  ('Corteva','workday','corteva','https://corteva.wd5.myworkdayjobs.com/wday/cxs/corteva/Corteva','hot',true,now(),'6 hours'),
  ('Cox Communications','workday','cox','https://cox.wd1.myworkdayjobs.com/wday/cxs/cox/Cox_External_Career_Site_1','hot',true,now(),'6 hours'),
  ('Crown Holdings','workday','crownholdings','https://crownholdings.wd501.myworkdayjobs.com/wday/cxs/crownholdings/CrownHoldings','hot',true,now(),'6 hours'),
  ('CSL Behring','workday','csl','https://csl.wd1.myworkdayjobs.com/wday/cxs/csl/CSL_External','hot',true,now(),'6 hours'),
  ('CVS Health','workday','cvshealth','https://cvshealth.wd1.myworkdayjobs.com/wday/cxs/cvshealth/CVS_Health_Careers','hot',true,now(),'6 hours'),
  ('Danaher','workday','danaher','https://danaher.wd1.myworkdayjobs.com/wday/cxs/danaher/DanaherJobs','hot',true,now(),'6 hours'),
  ('DaVita','workday','davita','https://davita.wd1.myworkdayjobs.com/wday/cxs/davita/DKC_External','hot',true,now(),'6 hours'),
  ('Dexcom','workday','dexcom','https://dexcom.wd1.myworkdayjobs.com/wday/cxs/dexcom/Dexcom','hot',true,now(),'6 hours'),
  ('Dow','workday','dow','https://dow.wd1.myworkdayjobs.com/wday/cxs/dow/ExternalCareers','hot',true,now(),'6 hours'),
  ('DuPont','workday','dupont','https://dupont.wd5.myworkdayjobs.com/wday/cxs/dupont/Jobs','hot',true,now(),'6 hours'),
  ('eBay','workday','ebay','https://ebay.wd5.myworkdayjobs.com/wday/cxs/ebay/apply','hot',true,now(),'6 hours'),
  ('Ecolab','workday','ecolab','https://ecolab.wd1.myworkdayjobs.com/wday/cxs/ecolab/Ecolab_External','hot',true,now(),'6 hours'),
  ('Edwards Lifesciences','workday','edwards','https://edwards.wd5.myworkdayjobs.com/wday/cxs/edwards/EdwardsCareers','hot',true,now(),'6 hours'),
  ('Elevance Health','workday','elevancehealth','https://elevancehealth.wd1.myworkdayjobs.com/wday/cxs/elevancehealth/ANT','hot',true,now(),'6 hours'),
  ('FedEx','workday','fedex','https://fedex.wd1.myworkdayjobs.com/wday/cxs/fedex/FXE-LAC_External_Career_Site','hot',true,now(),'6 hours'),
  ('Fifth Third Bank','workday','fifththird','https://fifththird.wd5.myworkdayjobs.com/wday/cxs/fifththird/53careers','hot',true,now(),'6 hours'),
  ('FIS','workday','fis','https://fis.wd5.myworkdayjobs.com/wday/cxs/fis/SearchJobs','hot',true,now(),'6 hours'),
  ('Fiserv','workday','fiserv','https://fiserv.wd5.myworkdayjobs.com/wday/cxs/fiserv/EXT','hot',true,now(),'6 hours'),
  ('Franklin Templeton','workday','franklintempleton','https://franklintempleton.wd5.myworkdayjobs.com/wday/cxs/franklintempleton/Primary-External-1','hot',true,now(),'6 hours'),
  ('Fresenius Medical Care','workday','freseniusmedicalcare','https://freseniusmedicalcare.wd3.myworkdayjobs.com/wday/cxs/freseniusmedicalcare/fme','hot',true,now(),'6 hours'),
  ('GE HealthCare','workday','gehc','https://gehc.wd5.myworkdayjobs.com/wday/cxs/gehc/GEHC_ExternalSite','hot',true,now(),'6 hours'),
  ('Genesys','workday','genesys','https://genesys.wd1.myworkdayjobs.com/wday/cxs/genesys/Genesys','hot',true,now(),'6 hours'),
  ('Gilead Sciences','workday','gilead','https://gilead.wd1.myworkdayjobs.com/wday/cxs/gilead/gileadcareers','hot',true,now(),'6 hours'),
  ('Global Payments','workday','tsys','https://tsys.wd1.myworkdayjobs.com/wday/cxs/tsys/TSYS','hot',true,now(),'6 hours'),
  ('Globe Life','workday','globelife','https://globelife.wd5.myworkdayjobs.com/wday/cxs/globelife/Globe-Life-Careers','hot',true,now(),'6 hours'),
  ('GSK','workday','gsk','https://gsk.wd5.myworkdayjobs.com/wday/cxs/gsk/GSKCareers','hot',true,now(),'6 hours'),
  ('Guardian Life','workday','guardianlife','https://guardianlife.wd5.myworkdayjobs.com/wday/cxs/guardianlife/Guardian-Life-Careers','hot',true,now(),'6 hours'),
  ('Guidewire Software','workday','guidewire','https://guidewire.wd5.myworkdayjobs.com/wday/cxs/guidewire/external','hot',true,now(),'6 hours'),
  ('Henry Schein','workday','henryschein','https://henryschein.wd1.myworkdayjobs.com/wday/cxs/henryschein/External_Careers','hot',true,now(),'6 hours'),
  ('Hewlett Packard Enterprise','workday','hpe','https://hpe.wd5.myworkdayjobs.com/wday/cxs/hpe/Jobsathpe','hot',true,now(),'6 hours'),
  ('Highmark Health','workday','highmarkhealth','https://highmarkhealth.wd1.myworkdayjobs.com/wday/cxs/highmarkhealth/highmark','hot',true,now(),'6 hours'),
  ('HP','workday','hp','https://hp.wd5.myworkdayjobs.com/wday/cxs/hp/ExternalCareerSite','hot',true,now(),'6 hours'),
  ('Humana','workday','humana','https://humana.wd5.myworkdayjobs.com/wday/cxs/humana/Humana_External_Career_Site','hot',true,now(),'6 hours'),
  ('Huntington Bancshares','workday','huntington','https://huntington.wd12.myworkdayjobs.com/wday/cxs/huntington/HNBcareers','hot',true,now(),'6 hours'),
  ('ICON plc','workday','icon','https://icon.wd3.myworkdayjobs.com/wday/cxs/icon/broadbean_external','hot',true,now(),'6 hours'),
  ('Illumina','workday','illumina','https://illumina.wd1.myworkdayjobs.com/wday/cxs/illumina/illumina-careers','hot',true,now(),'6 hours'),
  ('Insulet','workday','insulet','https://insulet.wd5.myworkdayjobs.com/wday/cxs/insulet/insuletcareers','hot',true,now(),'6 hours'),
  ('Intel','workday','intel','https://intel.wd1.myworkdayjobs.com/wday/cxs/intel/External','hot',true,now(),'6 hours'),
  ('Intuitive Surgical','workday','intuitive','https://intuitive.wd1.myworkdayjobs.com/wday/cxs/intuitive/irtc_careers','hot',true,now(),'6 hours'),
  ('Invesco','workday','invesco','https://invesco.wd1.myworkdayjobs.com/wday/cxs/invesco/IVZ','hot',true,now(),'6 hours'),
  ('IQVIA','workday','iqvia','https://iqvia.wd1.myworkdayjobs.com/wday/cxs/iqvia/IQVIA','hot',true,now(),'6 hours'),
  ('J.B. Hunt','workday','jbhunt','https://jbhunt.wd501.myworkdayjobs.com/wday/cxs/jbhunt/Careers','hot',true,now(),'6 hours'),
  ('Johnson & Johnson','workday','jj','https://jj.wd5.myworkdayjobs.com/wday/cxs/jj/JJ','hot',true,now(),'6 hours'),
  ('Johnson Controls','workday','jci','https://jci.wd5.myworkdayjobs.com/wday/cxs/jci/JCI','hot',true,now(),'6 hours'),
  ('KeyBank','workday','keybank','https://keybank.wd5.myworkdayjobs.com/wday/cxs/keybank/External_Career_Site','hot',true,now(),'6 hours'),
  ('Kimberly-Clark','workday','kimberlyclark','https://kimberlyclark.wd1.myworkdayjobs.com/wday/cxs/kimberlyclark/GLOBAL','hot',true,now(),'6 hours'),
  ('KLA','workday','kla','https://kla.wd1.myworkdayjobs.com/wday/cxs/kla/Search','hot',true,now(),'6 hours'),
  ('Kraft Heinz','workday','heinz','https://heinz.wd1.myworkdayjobs.com/wday/cxs/heinz/KraftHeinz_Careers','hot',true,now(),'6 hours'),
  ('Labcorp','workday','labcorp','https://labcorp.wd1.myworkdayjobs.com/wday/cxs/labcorp/External','hot',true,now(),'6 hours'),
  ('Las Vegas Sands','workday','sands','https://sands.wd1.myworkdayjobs.com/wday/cxs/sands/sands_careers','hot',true,now(),'6 hours'),
  ('Lowe''s','workday','lowes','https://lowes.wd5.myworkdayjobs.com/wday/cxs/lowes/LWS_External_CS','hot',true,now(),'6 hours'),
  ('M&T Bank','workday','mtb','https://mtb.wd5.myworkdayjobs.com/wday/cxs/mtb/MTB','hot',true,now(),'6 hours'),
  ('Markel','workday','markelcorp','https://markelcorp.wd5.myworkdayjobs.com/wday/cxs/markelcorp/GlobalCareers','hot',true,now(),'6 hours'),
  ('Marvell','workday','marvell','https://marvell.wd1.myworkdayjobs.com/wday/cxs/marvell/MarvellCareers','hot',true,now(),'6 hours'),
  ('MassMutual','workday','massmutual','https://massmutual.wd1.myworkdayjobs.com/wday/cxs/massmutual/MMAscendCareers','hot',true,now(),'6 hours'),
  ('Mastercard','workday','mastercard','https://mastercard.wd1.myworkdayjobs.com/wday/cxs/mastercard/CorporateCareers','hot',true,now(),'6 hours'),
  ('McKesson','workday','mckesson','https://mckesson.wd3.myworkdayjobs.com/wday/cxs/mckesson/External_Careers','hot',true,now(),'6 hours'),
  ('Medtronic','workday','medtronic','https://medtronic.wd1.myworkdayjobs.com/wday/cxs/medtronic/MedtronicCareers','hot',true,now(),'6 hours'),
  ('Merck','workday','msd','https://msd.wd5.myworkdayjobs.com/wday/cxs/msd/SearchJobs','hot',true,now(),'6 hours'),
  ('MGM Resorts','workday','mgmresorts','https://mgmresorts.wd5.myworkdayjobs.com/wday/cxs/mgmresorts/MGMCareers','hot',true,now(),'6 hours'),
  ('Micron Technology','workday','micron','https://micron.wd1.myworkdayjobs.com/wday/cxs/micron/External','hot',true,now(),'6 hours'),
  ('Moderna','workday','modernatx','https://modernatx.wd1.myworkdayjobs.com/wday/cxs/modernatx/M_tx','hot',true,now(),'6 hours'),
  ('Mondelez','workday','mdlz','https://mdlz.wd3.myworkdayjobs.com/wday/cxs/mdlz/External','hot',true,now(),'6 hours'),
  ('Morgan Stanley','workday','ms','https://ms.wd5.myworkdayjobs.com/wday/cxs/ms/External','hot',true,now(),'6 hours'),
  ('Nasdaq','workday','nasdaq','https://nasdaq.wd1.myworkdayjobs.com/wday/cxs/nasdaq/US_External_Career_Site','hot',true,now(),'6 hours'),
  ('Nationwide','workday','nationwide','https://nationwide.wd1.myworkdayjobs.com/wday/cxs/nationwide/Nationwide_Career','hot',true,now(),'6 hours'),
  ('Neurocrine Biosciences','workday','neurocrine','https://neurocrine.wd5.myworkdayjobs.com/wday/cxs/neurocrine/Neurocrinecareers','hot',true,now(),'6 hours'),
  ('Nike','workday','nike','https://nike.wd1.myworkdayjobs.com/wday/cxs/nike/nke','hot',true,now(),'6 hours'),
  ('Northern Trust','workday','ntrs','https://ntrs.wd1.myworkdayjobs.com/wday/cxs/ntrs/northerntrust','hot',true,now(),'6 hours'),
  ('Northrop Grumman','workday','ngc','https://ngc.wd1.myworkdayjobs.com/wday/cxs/ngc/Northrop_Grumman_External_Site','hot',true,now(),'6 hours'),
  ('Northwestern Mutual','workday','northwesternmutual','https://northwesternmutual.wd5.myworkdayjobs.com/wday/cxs/northwesternmutual/CORPORATE-CAREERS','hot',true,now(),'6 hours'),
  ('Novartis','workday','novartis','https://novartis.wd3.myworkdayjobs.com/wday/cxs/novartis/Novartis_Careers','hot',true,now(),'6 hours'),
  ('O''Reilly Automotive','workday','oreillyauto','https://oreillyauto.wd1.myworkdayjobs.com/wday/cxs/oreillyauto/oreilly','hot',true,now(),'6 hours'),
  ('Old Dominion','workday','odfl','https://odfl.wd1.myworkdayjobs.com/wday/cxs/odfl/ODFL_Careers','hot',true,now(),'6 hours'),
  ('Organon','workday','organon','https://organon.wd5.myworkdayjobs.com/wday/cxs/organon/SearchJobs','hot',true,now(),'6 hours'),
  ('Oshkosh','workday','oshkoshcorporation','https://oshkoshcorporation.wd5.myworkdayjobs.com/wday/cxs/oshkoshcorporation/Oshkosh','hot',true,now(),'6 hours'),
  ('Otis Worldwide','workday','otis','https://otis.wd5.myworkdayjobs.com/wday/cxs/otis/REC_Ext_Gateway','hot',true,now(),'6 hours'),
  ('Pacific Life','workday','pacificlife','https://pacificlife.wd1.myworkdayjobs.com/wday/cxs/pacificlife/PacificLifeCareers','hot',true,now(),'6 hours'),
  ('PayPal','workday','paypal','https://paypal.wd1.myworkdayjobs.com/wday/cxs/paypal/jobs','hot',true,now(),'6 hours'),
  ('Pentair','workday','pentair','https://pentair.wd5.myworkdayjobs.com/wday/cxs/pentair/Pentair_Careers','hot',true,now(),'6 hours'),
  ('Pfizer','workday','pfizer','https://pfizer.wd1.myworkdayjobs.com/wday/cxs/pfizer/PfizerCareers','hot',true,now(),'6 hours'),
  ('PNC Financial','workday','pnc','https://pnc.wd5.myworkdayjobs.com/wday/cxs/pnc/External','hot',true,now(),'6 hours'),
  ('Principal Financial Group','workday','thegroove','https://thegroove.wd12.myworkdayjobs.com/wday/cxs/thegroove/thegroovecareers','hot',true,now(),'6 hours'),
  ('Prudential Financial','workday','pru','https://pru.wd5.myworkdayjobs.com/wday/cxs/pru/Careers','hot',true,now(),'6 hours'),
  ('PTC','workday','ptc','https://ptc.wd1.myworkdayjobs.com/wday/cxs/ptc/PTC','hot',true,now(),'6 hours'),
  ('QIAGEN','workday','qiagen','https://qiagen.wd502.myworkdayjobs.com/wday/cxs/qiagen/QIAGEN','hot',true,now(),'6 hours'),
  ('Raymond James','workday','raymondjames','https://raymondjames.wd1.myworkdayjobs.com/wday/cxs/raymondjames/RaymondJamesCareers','hot',true,now(),'6 hours'),
  ('Regeneron','workday','regeneron','https://regeneron.wd1.myworkdayjobs.com/wday/cxs/regeneron/Careers','hot',true,now(),'6 hours'),
  ('Regions Financial','workday','regions','https://regions.wd5.myworkdayjobs.com/wday/cxs/regions/Regions_Careers','hot',true,now(),'6 hours'),
  ('ResMed','workday','resmed','https://resmed.wd3.myworkdayjobs.com/wday/cxs/resmed/ResMed_External_Careers','hot',true,now(),'6 hours'),
  ('Revvity','workday','revvity','https://revvity.wd103.myworkdayjobs.com/wday/cxs/revvity/External','hot',true,now(),'6 hours'),
  ('Roche','workday','roche','https://roche.wd3.myworkdayjobs.com/wday/cxs/roche/roche-ext','hot',true,now(),'6 hours'),
  ('Rockwell Automation','workday','rockwellautomation','https://rockwellautomation.wd1.myworkdayjobs.com/wday/cxs/rockwellautomation/External_Rockwell_Automation','hot',true,now(),'6 hours'),
  ('RTX','workday','globalhr','https://globalhr.wd5.myworkdayjobs.com/wday/cxs/globalhr/REC_RTX_Ext_Gateway','hot',true,now(),'6 hours'),
  ('Ryder','workday','ryder','https://ryder.wd5.myworkdayjobs.com/wday/cxs/ryder/RyderCareers','hot',true,now(),'6 hours'),
  ('S&P Global','workday','spgi','https://spgi.wd5.myworkdayjobs.com/wday/cxs/spgi/SPGI_Careers','hot',true,now(),'6 hours'),
  ('Salesforce','workday','salesforce','https://salesforce.wd12.myworkdayjobs.com/wday/cxs/salesforce/External_Career_Site','hot',true,now(),'6 hours'),
  ('Sanofi','workday','sanofi','https://sanofi.wd3.myworkdayjobs.com/wday/cxs/sanofi/SanofiCareers','hot',true,now(),'6 hours'),
  ('Sarepta Therapeutics','workday','sarepta','https://sarepta.wd5.myworkdayjobs.com/wday/cxs/sarepta/sarepta_external','hot',true,now(),'6 hours'),
  ('Siemens Healthineers','workday','onehealthineers','https://onehealthineers.wd3.myworkdayjobs.com/wday/cxs/onehealthineers/SHSJB','hot',true,now(),'6 hours'),
  ('Snap','workday','snapchat','https://snapchat.wd1.myworkdayjobs.com/wday/cxs/snapchat/snap','hot',true,now(),'6 hours'),
  ('Stanley Black & Decker','workday','sbdinc','https://sbdinc.wd1.myworkdayjobs.com/wday/cxs/sbdinc/Stanley_Black_Decker_Career_Site','hot',true,now(),'6 hours'),
  ('State Street','workday','statestreet','https://statestreet.wd1.myworkdayjobs.com/wday/cxs/statestreet/Global','hot',true,now(),'6 hours'),
  ('Stryker','workday','stryker','https://stryker.wd1.myworkdayjobs.com/wday/cxs/stryker/StrykerCareers','hot',true,now(),'6 hours'),
  ('Synchrony','workday','synchronyfinancial','https://synchronyfinancial.wd5.myworkdayjobs.com/wday/cxs/synchronyfinancial/careers','hot',true,now(),'6 hours'),
  ('T-Mobile','workday','tmobile','https://tmobile.wd1.myworkdayjobs.com/wday/cxs/tmobile/External','hot',true,now(),'6 hours'),
  ('T. Rowe Price','workday','troweprice','https://troweprice.wd5.myworkdayjobs.com/wday/cxs/troweprice/TRowePrice','hot',true,now(),'6 hours'),
  ('Takeda','workday','takeda','https://takeda.wd3.myworkdayjobs.com/wday/cxs/takeda/External','hot',true,now(),'6 hours'),
  ('Tapestry','workday','tapestry','https://tapestry.wd108.myworkdayjobs.com/wday/cxs/tapestry/Tapestry_Careers','hot',true,now(),'6 hours'),
  ('Target','workday','target','https://target.wd5.myworkdayjobs.com/wday/cxs/target/targetcareers','hot',true,now(),'6 hours'),
  ('The Hartford','workday','thehartford','https://thehartford.wd5.myworkdayjobs.com/wday/cxs/thehartford/Careers_External','hot',true,now(),'6 hours'),
  ('Thermo Fisher Scientific','workday','thermofisher','https://thermofisher.wd5.myworkdayjobs.com/wday/cxs/thermofisher/ThermoFisherCareers','hot',true,now(),'6 hours'),
  ('TIAA','workday','tiaa','https://tiaa.wd1.myworkdayjobs.com/wday/cxs/tiaa/Search','hot',true,now(),'6 hours'),
  ('TJX Companies','workday','tjx','https://tjx.wd1.myworkdayjobs.com/wday/cxs/tjx/TJX_EXTERNAL','hot',true,now(),'6 hours'),
  ('Trane Technologies','workday','tranetechnologies','https://tranetechnologies.wd12.myworkdayjobs.com/wday/cxs/tranetechnologies/Trane_Technologies_Careers','hot',true,now(),'6 hours'),
  ('Travelers','workday','travelers','https://travelers.wd5.myworkdayjobs.com/wday/cxs/travelers/External','hot',true,now(),'6 hours'),
  ('Truist','workday','truist','https://truist.wd1.myworkdayjobs.com/wday/cxs/truist/Careers','hot',true,now(),'6 hours'),
  ('Tyson Foods','workday','tysonfoods','https://tysonfoods.wd5.myworkdayjobs.com/wday/cxs/tysonfoods/TSN','hot',true,now(),'6 hours'),
  ('U.S. Bank','workday','usbank','https://usbank.wd1.myworkdayjobs.com/wday/cxs/usbank/US_Bank_Careers','hot',true,now(),'6 hours'),
  ('Unum','workday','unum','https://unum.wd1.myworkdayjobs.com/wday/cxs/unum/External','hot',true,now(),'6 hours'),
  ('USAA','workday','usaa','https://usaa.wd1.myworkdayjobs.com/wday/cxs/usaa/USAAJOBSWD','hot',true,now(),'6 hours'),
  ('Vanguard','workday','vanguard','https://vanguard.wd5.myworkdayjobs.com/wday/cxs/vanguard/vanguard_external','hot',true,now(),'6 hours'),
  ('Verizon','workday','verizon','https://verizon.wd12.myworkdayjobs.com/wday/cxs/verizon/verizon-careers','hot',true,now(),'6 hours'),
  ('Vertex Pharmaceuticals','workday','vrtx','https://vrtx.wd501.myworkdayjobs.com/wday/cxs/vrtx/Vertex_Careers','hot',true,now(),'6 hours'),
  ('VF Corporation','workday','vfc','https://vfc.wd5.myworkdayjobs.com/wday/cxs/vfc/vfc_careers','hot',true,now(),'6 hours'),
  ('Viatris','workday','viatris','https://viatris.wd5.myworkdayjobs.com/wday/cxs/viatris/External','hot',true,now(),'6 hours'),
  ('Visa','workday','visa','https://visa.wd5.myworkdayjobs.com/wday/cxs/visa/Visa','hot',true,now(),'6 hours'),
  ('Voya Financial','workday','godirect','https://godirect.wd5.myworkdayjobs.com/wday/cxs/godirect/voya_jobs','hot',true,now(),'6 hours'),
  ('Warner Bros Discovery','workday','warnerbros','https://warnerbros.wd5.myworkdayjobs.com/wday/cxs/warnerbros/global','hot',true,now(),'6 hours'),
  ('Wells Fargo','workday','wf','https://wf.wd1.myworkdayjobs.com/wday/cxs/wf/WellsFargoJobs','hot',true,now(),'6 hours'),
  ('Western Union','workday','westernunion','https://westernunion.wd5.myworkdayjobs.com/wday/cxs/westernunion/WesternUnionJobs','hot',true,now(),'6 hours'),
  ('Workday','workday','workday','https://workday.wd5.myworkdayjobs.com/wday/cxs/workday/Workday','hot',true,now(),'6 hours'),
  ('Workiva','workday','workiva','https://workiva.wd503.myworkdayjobs.com/wday/cxs/workiva/careers','hot',true,now(),'6 hours'),
  ('Worldpay','workday','worldpay','https://worldpay.wd5.myworkdayjobs.com/wday/cxs/worldpay/Worldpay_External_Careers_Site','hot',true,now(),'6 hours'),
  ('Wyndham','workday','wynd','https://wynd.wd5.myworkdayjobs.com/wday/cxs/wynd/External','hot',true,now(),'6 hours'),
  ('Xylem','workday','xylem','https://xylem.wd5.myworkdayjobs.com/wday/cxs/xylem/xylem-careers','hot',true,now(),'6 hours'),
  ('Zebra Technologies','workday','zebra','https://zebra.wd501.myworkdayjobs.com/wday/cxs/zebra/Zebra_careers','hot',true,now(),'6 hours'),
  ('Zendesk','workday','zendesk','https://zendesk.wd1.myworkdayjobs.com/wday/cxs/zendesk/zendesk','hot',true,now(),'6 hours'),
  ('Zoom','workday','zoom','https://zoom.wd5.myworkdayjobs.com/wday/cxs/zoom/Zoom','hot',true,now(),'6 hours')
ON CONFLICT (ats_type, slug) DO UPDATE SET
  name=EXCLUDED.name, api_base=EXCLUDED.api_base, tier='hot', is_active=true, next_poll_at=now();

INSERT INTO company_tiers (name_norm, tier, canonical, notes) VALUES
  (cf_name_norm('3M'),'B','3M','workday'),
  (cf_name_norm('Abbott'),'B','Abbott','workday'),
  (cf_name_norm('Adobe'),'A','Adobe','workday'),
  (cf_name_norm('Agilent Technologies'),'B','Agilent Technologies','workday'),
  (cf_name_norm('AIG'),'B','AIG','workday'),
  (cf_name_norm('Albemarle'),'B','Albemarle','workday'),
  (cf_name_norm('Allstate'),'B','Allstate','workday'),
  (cf_name_norm('Ameriprise Financial'),'A','Ameriprise Financial','workday'),
  (cf_name_norm('Amgen'),'B','Amgen','workday'),
  (cf_name_norm('Analog Devices'),'A','Analog Devices','workday'),
  (cf_name_norm('Applied Materials'),'A','Applied Materials','workday'),
  (cf_name_norm('Assurant'),'B','Assurant','workday'),
  (cf_name_norm('AstraZeneca'),'B','AstraZeneca','workday'),
  (cf_name_norm('AT&T'),'B','AT&T','workday'),
  (cf_name_norm('Autodesk'),'A','Autodesk','workday'),
  (cf_name_norm('Avantor'),'B','Avantor','workday'),
  (cf_name_norm('Bank of America'),'A','Bank of America','workday'),
  (cf_name_norm('Baxter International'),'B','Baxter International','workday'),
  (cf_name_norm('Becton Dickinson'),'B','Becton Dickinson','workday'),
  (cf_name_norm('Best Buy'),'B','Best Buy','workday'),
  (cf_name_norm('Biogen'),'B','Biogen','workday'),
  (cf_name_norm('BlackRock'),'A','BlackRock','workday'),
  (cf_name_norm('Boeing'),'B','Boeing','workday'),
  (cf_name_norm('Bread Financial'),'B','Bread Financial','workday'),
  (cf_name_norm('Bristol Myers Squibb'),'B','Bristol Myers Squibb','workday'),
  (cf_name_norm('Broadcom'),'A','Broadcom','workday'),
  (cf_name_norm('C.H. Robinson'),'B','C.H. Robinson','workday'),
  (cf_name_norm('Cadence Design Systems'),'A','Cadence Design Systems','workday'),
  (cf_name_norm('Campbell Soup'),'B','Campbell Soup','workday'),
  (cf_name_norm('Capital One'),'A','Capital One','workday'),
  (cf_name_norm('Cardinal Health'),'B','Cardinal Health','workday'),
  (cf_name_norm('Catalent'),'B','Catalent','workday'),
  (cf_name_norm('Caterpillar'),'B','Caterpillar','workday'),
  (cf_name_norm('Cencora'),'B','Cencora','workday'),
  (cf_name_norm('Centene'),'B','Centene','workday'),
  (cf_name_norm('Church & Dwight'),'B','Church & Dwight','workday'),
  (cf_name_norm('Cigna'),'B','Cigna','workday'),
  (cf_name_norm('Cisco'),'A','Cisco','workday'),
  (cf_name_norm('Citi'),'A','Citi','workday'),
  (cf_name_norm('Clorox'),'B','Clorox','workday'),
  (cf_name_norm('Comcast'),'B','Comcast','workday'),
  (cf_name_norm('Conagra Brands'),'B','Conagra Brands','workday'),
  (cf_name_norm('Constellation Brands'),'B','Constellation Brands','workday'),
  (cf_name_norm('Corteva'),'B','Corteva','workday'),
  (cf_name_norm('Cox Communications'),'B','Cox Communications','workday'),
  (cf_name_norm('Crown Holdings'),'B','Crown Holdings','workday'),
  (cf_name_norm('CSL Behring'),'B','CSL Behring','workday'),
  (cf_name_norm('CVS Health'),'B','CVS Health','workday'),
  (cf_name_norm('Danaher'),'B','Danaher','workday'),
  (cf_name_norm('DaVita'),'B','DaVita','workday'),
  (cf_name_norm('Dexcom'),'B','Dexcom','workday'),
  (cf_name_norm('Dow'),'B','Dow','workday'),
  (cf_name_norm('DuPont'),'B','DuPont','workday'),
  (cf_name_norm('eBay'),'A','eBay','workday'),
  (cf_name_norm('Ecolab'),'B','Ecolab','workday'),
  (cf_name_norm('Edwards Lifesciences'),'B','Edwards Lifesciences','workday'),
  (cf_name_norm('Elevance Health'),'B','Elevance Health','workday'),
  (cf_name_norm('FedEx'),'B','FedEx','workday'),
  (cf_name_norm('Fifth Third Bank'),'A','Fifth Third Bank','workday'),
  (cf_name_norm('FIS'),'A','FIS','workday'),
  (cf_name_norm('Fiserv'),'A','Fiserv','workday'),
  (cf_name_norm('Franklin Templeton'),'A','Franklin Templeton','workday'),
  (cf_name_norm('Fresenius Medical Care'),'B','Fresenius Medical Care','workday'),
  (cf_name_norm('GE HealthCare'),'B','GE HealthCare','workday'),
  (cf_name_norm('Genesys'),'A','Genesys','workday'),
  (cf_name_norm('Gilead Sciences'),'B','Gilead Sciences','workday'),
  (cf_name_norm('Global Payments'),'A','Global Payments','workday'),
  (cf_name_norm('Globe Life'),'B','Globe Life','workday'),
  (cf_name_norm('GSK'),'B','GSK','workday'),
  (cf_name_norm('Guardian Life'),'B','Guardian Life','workday'),
  (cf_name_norm('Guidewire Software'),'A','Guidewire Software','workday'),
  (cf_name_norm('Henry Schein'),'B','Henry Schein','workday'),
  (cf_name_norm('Hewlett Packard Enterprise'),'B','Hewlett Packard Enterprise','workday'),
  (cf_name_norm('Highmark Health'),'B','Highmark Health','workday'),
  (cf_name_norm('HP'),'B','HP','workday'),
  (cf_name_norm('Humana'),'B','Humana','workday'),
  (cf_name_norm('Huntington Bancshares'),'A','Huntington Bancshares','workday'),
  (cf_name_norm('ICON plc'),'B','ICON plc','workday'),
  (cf_name_norm('Illumina'),'B','Illumina','workday'),
  (cf_name_norm('Insulet'),'B','Insulet','workday'),
  (cf_name_norm('Intel'),'A','Intel','workday'),
  (cf_name_norm('Intuitive Surgical'),'B','Intuitive Surgical','workday'),
  (cf_name_norm('Invesco'),'A','Invesco','workday'),
  (cf_name_norm('IQVIA'),'B','IQVIA','workday'),
  (cf_name_norm('J.B. Hunt'),'B','J.B. Hunt','workday'),
  (cf_name_norm('Johnson & Johnson'),'B','Johnson & Johnson','workday'),
  (cf_name_norm('Johnson Controls'),'B','Johnson Controls','workday'),
  (cf_name_norm('KeyBank'),'A','KeyBank','workday'),
  (cf_name_norm('Kimberly-Clark'),'B','Kimberly-Clark','workday'),
  (cf_name_norm('KLA'),'A','KLA','workday'),
  (cf_name_norm('Kraft Heinz'),'B','Kraft Heinz','workday'),
  (cf_name_norm('Labcorp'),'B','Labcorp','workday'),
  (cf_name_norm('Las Vegas Sands'),'B','Las Vegas Sands','workday'),
  (cf_name_norm('Lowe''s'),'B','Lowe''s','workday'),
  (cf_name_norm('M&T Bank'),'A','M&T Bank','workday'),
  (cf_name_norm('Markel'),'B','Markel','workday'),
  (cf_name_norm('Marvell'),'A','Marvell','workday'),
  (cf_name_norm('MassMutual'),'B','MassMutual','workday'),
  (cf_name_norm('Mastercard'),'A','Mastercard','workday'),
  (cf_name_norm('McKesson'),'B','McKesson','workday'),
  (cf_name_norm('Medtronic'),'B','Medtronic','workday'),
  (cf_name_norm('Merck'),'B','Merck','workday'),
  (cf_name_norm('MGM Resorts'),'B','MGM Resorts','workday'),
  (cf_name_norm('Micron Technology'),'A','Micron Technology','workday'),
  (cf_name_norm('Moderna'),'B','Moderna','workday'),
  (cf_name_norm('Mondelez'),'B','Mondelez','workday'),
  (cf_name_norm('Morgan Stanley'),'A','Morgan Stanley','workday'),
  (cf_name_norm('Nasdaq'),'A','Nasdaq','workday'),
  (cf_name_norm('Nationwide'),'B','Nationwide','workday'),
  (cf_name_norm('Neurocrine Biosciences'),'B','Neurocrine Biosciences','workday'),
  (cf_name_norm('Nike'),'B','Nike','workday'),
  (cf_name_norm('Northern Trust'),'A','Northern Trust','workday'),
  (cf_name_norm('Northrop Grumman'),'B','Northrop Grumman','workday'),
  (cf_name_norm('Northwestern Mutual'),'B','Northwestern Mutual','workday'),
  (cf_name_norm('Novartis'),'B','Novartis','workday'),
  (cf_name_norm('O''Reilly Automotive'),'B','O''Reilly Automotive','workday'),
  (cf_name_norm('Old Dominion'),'B','Old Dominion','workday'),
  (cf_name_norm('Organon'),'B','Organon','workday'),
  (cf_name_norm('Oshkosh'),'B','Oshkosh','workday'),
  (cf_name_norm('Otis Worldwide'),'B','Otis Worldwide','workday'),
  (cf_name_norm('Pacific Life'),'B','Pacific Life','workday'),
  (cf_name_norm('PayPal'),'A','PayPal','workday'),
  (cf_name_norm('Pentair'),'B','Pentair','workday'),
  (cf_name_norm('Pfizer'),'B','Pfizer','workday'),
  (cf_name_norm('PNC Financial'),'A','PNC Financial','workday'),
  (cf_name_norm('Principal Financial Group'),'B','Principal Financial Group','workday'),
  (cf_name_norm('Prudential Financial'),'B','Prudential Financial','workday'),
  (cf_name_norm('PTC'),'A','PTC','workday'),
  (cf_name_norm('QIAGEN'),'B','QIAGEN','workday'),
  (cf_name_norm('Raymond James'),'A','Raymond James','workday'),
  (cf_name_norm('Regeneron'),'B','Regeneron','workday'),
  (cf_name_norm('Regions Financial'),'A','Regions Financial','workday'),
  (cf_name_norm('ResMed'),'B','ResMed','workday'),
  (cf_name_norm('Revvity'),'B','Revvity','workday'),
  (cf_name_norm('Roche'),'B','Roche','workday'),
  (cf_name_norm('Rockwell Automation'),'B','Rockwell Automation','workday'),
  (cf_name_norm('RTX'),'B','RTX','workday'),
  (cf_name_norm('Ryder'),'B','Ryder','workday'),
  (cf_name_norm('S&P Global'),'A','S&P Global','workday'),
  (cf_name_norm('Salesforce'),'A','Salesforce','workday'),
  (cf_name_norm('Sanofi'),'B','Sanofi','workday'),
  (cf_name_norm('Sarepta Therapeutics'),'B','Sarepta Therapeutics','workday'),
  (cf_name_norm('Siemens Healthineers'),'B','Siemens Healthineers','workday'),
  (cf_name_norm('Snap'),'A','Snap','workday'),
  (cf_name_norm('Stanley Black & Decker'),'B','Stanley Black & Decker','workday'),
  (cf_name_norm('State Street'),'A','State Street','workday'),
  (cf_name_norm('Stryker'),'B','Stryker','workday'),
  (cf_name_norm('Synchrony'),'A','Synchrony','workday'),
  (cf_name_norm('T-Mobile'),'B','T-Mobile','workday'),
  (cf_name_norm('T. Rowe Price'),'A','T. Rowe Price','workday'),
  (cf_name_norm('Takeda'),'B','Takeda','workday'),
  (cf_name_norm('Tapestry'),'B','Tapestry','workday'),
  (cf_name_norm('Target'),'B','Target','workday'),
  (cf_name_norm('The Hartford'),'B','The Hartford','workday'),
  (cf_name_norm('Thermo Fisher Scientific'),'B','Thermo Fisher Scientific','workday'),
  (cf_name_norm('TIAA'),'A','TIAA','workday'),
  (cf_name_norm('TJX Companies'),'B','TJX Companies','workday'),
  (cf_name_norm('Trane Technologies'),'B','Trane Technologies','workday'),
  (cf_name_norm('Travelers'),'B','Travelers','workday'),
  (cf_name_norm('Truist'),'A','Truist','workday'),
  (cf_name_norm('Tyson Foods'),'B','Tyson Foods','workday'),
  (cf_name_norm('U.S. Bank'),'A','U.S. Bank','workday'),
  (cf_name_norm('Unum'),'B','Unum','workday'),
  (cf_name_norm('USAA'),'B','USAA','workday'),
  (cf_name_norm('Vanguard'),'A','Vanguard','workday'),
  (cf_name_norm('Verizon'),'B','Verizon','workday'),
  (cf_name_norm('Vertex Pharmaceuticals'),'B','Vertex Pharmaceuticals','workday'),
  (cf_name_norm('VF Corporation'),'B','VF Corporation','workday'),
  (cf_name_norm('Viatris'),'B','Viatris','workday'),
  (cf_name_norm('Visa'),'A','Visa','workday'),
  (cf_name_norm('Voya Financial'),'B','Voya Financial','workday'),
  (cf_name_norm('Warner Bros Discovery'),'B','Warner Bros Discovery','workday'),
  (cf_name_norm('Wells Fargo'),'A','Wells Fargo','workday'),
  (cf_name_norm('Western Union'),'A','Western Union','workday'),
  (cf_name_norm('Workday'),'A','Workday','workday'),
  (cf_name_norm('Workiva'),'A','Workiva','workday'),
  (cf_name_norm('Worldpay'),'A','Worldpay','workday'),
  (cf_name_norm('Wyndham'),'B','Wyndham','workday'),
  (cf_name_norm('Xylem'),'B','Xylem','workday'),
  (cf_name_norm('Zebra Technologies'),'A','Zebra Technologies','workday'),
  (cf_name_norm('Zendesk'),'A','Zendesk','workday'),
  (cf_name_norm('Zoom'),'A','Zoom','workday')
ON CONFLICT (name_norm) DO UPDATE SET tier=EXCLUDED.tier, canonical=EXCLUDED.canonical, notes=EXCLUDED.notes, updated_at=now();
