/**
 * p2_source_policy.js -- inline the canonical scripts/nodes/_source_policy.js into the
 * affected Code nodes (n8n can't require local files) and splice them into the 3 modern
 * exports. Behavior-preserving centralization (P2): the inlined SOURCE_POLICY is the
 * SAME code the nodes used to define locally; nodes now alias it instead of duplicating.
 *
 *   - Aggregate Jobs      : drop local ATS_URL, BOARD_DENY, CAREERS heuristics and
 *                           isAtsDestination -> alias SOURCE_POLICY.isAtsDestination.
 *                           (STAFFING / LISTING_TITLE kept local -- not source policy.)
 *   - Normalize {Serper,Firecrawl,You.com}: drop the triplicated classifyUrlTier ->
 *                           alias SOURCE_POLICY.classifyUrlTier.
 *   - Build FC Queries    : standardATS -> SOURCE_POLICY.standardAtsDomains().
 *
 * NOT touched: build_serper_queries.js / build_youcom_queries.js -- their deterministic
 * site: query STRINGS use bespoke per-builder groupings; deriving them from a flat list
 * would change output. The canonical domain SET lives in standardAtsDomains() for reference.
 *
 * Idempotent (re-run refreshes only the policy block between markers). Backups + integrity.
 * Run: node scripts/p2_source_policy.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const NODES = path.join(__dirname, 'nodes');
const TARGETS = [
  path.join(ROOT, 'docker', 'workflows', 'CareerForge_Master_local.json'),
  path.join(ROOT, 'workflows', 'CareerForge_Master_local.json'),
  path.join(ROOT, 'docker', 'workflows', 'CareerForge Master Local v6.3.json'),
];
const BEGIN = '// === BEGIN _source_policy (generated by scripts/p2_source_policy.js -- edit scripts/nodes/_source_policy.js) ===';
const END = '// === END _source_policy ===';

const policySrc = fs.readFileSync(path.join(NODES, '_source_policy.js'), 'utf8');
const pStart = policySrc.indexOf('const SOURCE_POLICY = (function');
const pEnd = policySrc.indexOf('})();', pStart) + 5;
if (pStart < 0 || pEnd < 5) { console.error('cannot locate SOURCE_POLICY IIFE in _source_policy.js'); process.exit(1); }
const POLICY_BLOCK = policySrc.slice(pStart, pEnd);
const BLOCK = BEGIN + '\n' + POLICY_BLOCK + '\n' + END + '\n';

const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function braceEndAfter(src, openIdx) {
  let d = 0;
  for (let i = openIdx; i < src.length; i++) {
    if (src[i] === '{') d++;
    else if (src[i] === '}') { d--; if (d === 0) return i + 1; }
  }
  return -1;
}
function removeFn(body, name, commentMarker) {
  const fstart = body.indexOf('function ' + name);
  if (fstart < 0) return body;
  const cstart = commentMarker ? body.indexOf(commentMarker) : -1;
  const start = (cstart >= 0 && cstart < fstart) ? cstart : fstart;
  const end = braceEndAfter(body, body.indexOf('{', fstart));
  return body.slice(0, start) + body.slice(end).replace(/^\n+/, '');
}
function removeRange(body, startMarker, fnName) {
  const start = body.indexOf(startMarker);
  const fstart = body.indexOf('function ' + fnName);
  if (start < 0 || fstart < 0) return body;
  const end = braceEndAfter(body, body.indexOf('{', fstart));
  return body.slice(0, start) + body.slice(end).replace(/^\n+/, '');
}

function refactor(content, type) {
  if (content.includes(BEGIN)) {                                   // idempotent: refresh block only
    // function replacement -> BLOCK is inserted literally ($&/$1 in the policy body are NOT
    // treated as replacement patterns).
    return content.replace(new RegExp(esc(BEGIN) + '[\\s\\S]*?' + esc(END) + '\\n?'), () => BLOCK);
  }
  let body = content, alias = '';
  if (type === 'classifier') {
    body = removeFn(body, 'classifyUrlTier', '// --- URL Tier Classifier');
    alias = 'const classifyUrlTier = SOURCE_POLICY.classifyUrlTier;\n\n';
  } else if (type === 'aggregate') {
    body = removeRange(body, '// HARD POLICY', 'isAtsDestination');
    alias = '// Source policy (ATS allow / board deny / career heuristics / isAtsDestination)\n'
          + '// is centralized in _source_policy.js, inlined above as SOURCE_POLICY (P2).\n'
          + 'const isAtsDestination = SOURCE_POLICY.isAtsDestination;\n\n';
  } else if (type === 'fcdomains') {
    body = body.replace(/const standardATS = \[[\s\S]*?\];/, 'const standardATS = SOURCE_POLICY.standardAtsDomains();');
  }
  return BLOCK + '\n' + alias + body;
}

const MAP = [
  ['Aggregate Jobs', 'aggregate_jobs.js', 'aggregate'],
  ['Normalize Serper results', 'normalize_serper.js', 'classifier'],
  ['Normalize Firecrawl Results', 'normalize_firecrawl.js', 'classifier'],
  ['Normalize You.com results', 'normalize_youcom.js', 'classifier'],
  ['Build FC Queries', 'build_fc_queries.js', 'fcdomains'],
];

// 1) refactor canonical node files + parse-check
const BODIES = {};
for (const [nodeName, file, type] of MAP) {
  const p = path.join(NODES, file);
  const refactored = refactor(fs.readFileSync(p, 'utf8'), type);
  try { new Function('$input', '$', '$json', '$getWorkflowStaticData', '$env', refactored); }
  catch (e) { console.error('PARSE FAIL ' + file + ': ' + e.message); process.exit(1); }
  if (!/SOURCE_POLICY/.test(refactored)) { console.error('refactor produced no SOURCE_POLICY ref: ' + file); process.exit(1); }
  fs.writeFileSync(p, refactored);
  BODIES[nodeName] = refactored;
  console.log('refactored scripts/nodes/' + file);
}

// 2) splice into the 3 modern exports
const stamp = () => new Date().toISOString().replace(/[:.]/g, '-');
for (const file of TARGETS) {
  if (!fs.existsSync(file)) { console.log('SKIP (missing): ' + path.relative(ROOT, file)); continue; }
  const wf = JSON.parse(fs.readFileSync(file, 'utf8'));
  const N = {}; wf.nodes.forEach((n) => { N[n.name] = n; });
  const done = [], missing = [];
  for (const [nodeName] of MAP) {
    if (!N[nodeName]) { missing.push(nodeName); continue; }
    N[nodeName].parameters.jsCode = BODIES[nodeName];
    done.push(nodeName);
  }
  const names = new Set(wf.nodes.map((n) => n.name));
  for (const [src, obj] of Object.entries(wf.connections || {})) {
    if (!names.has(src)) { console.error('INTEGRITY FAIL: source ' + src); process.exit(1); }
    for (const branches of Object.values(obj)) (branches || []).forEach((br) => (br || []).forEach((e) => {
      if (!names.has(e.node)) { console.error('INTEGRITY FAIL ' + src + ' -> ' + e.node); process.exit(1); }
    }));
  }
  fs.writeFileSync(file + '.p2bak-' + stamp(), fs.readFileSync(file));
  fs.writeFileSync(file, JSON.stringify(wf, null, 2));
  console.log('OK ' + path.relative(ROOT, file) + ': spliced [' + done.join(', ') + ']' + (missing.length ? ' MISSING: ' + missing.join(', ') : ''));
}
console.log('p2_source_policy complete.');
